### ISSUE TITLE
使用根布局，会崩溃

### ISSUE THREAD

**Issue by hudan2714** [Bakumon/StatusLayoutManager#4]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
                                                                    at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4365)
                                                                    at android.view.ViewGroup.removeViewAt(ViewGroup.java:4327)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1586)
                                                                    at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:789)
                                                                    at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
                                                                    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2200)
                                                                    at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2153)
                                                                    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2063)
                                                                    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:725)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5418)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

能不能在自定义view上，自动给它包裹一个布局呢？

**Comment by hudan2714** [comment]
使用场景是这样的。一个activity里有一个frameLayout的container，里面放两个fragment，一个fragment用根布局显示statuslayou，切换这两个布局的时候，就会有问题，会出现上面的错误

**Comment by Bakumon** [comment]
最新版本1.0.2解决了这个问题，请升级版本
